receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: log-processor-pods
        scrape_interval: 15s
        scrape_timeout: 10s
        relabel_configs:
          - source_labels: [instance]
            action: replace
            target_label: instance
            replacement: log-processor

        static_configs:
          - targets: ['0.0.0.0:3000']

exporters:
  otlp:
    endpoint: "collector-pod:4317"
    tls:
      insecure: true
    sending_queue:
      num_consumers: 5
      queue_size: 1000
    retry_on_failure:
      enabled: 
  logging: {}

processors:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 50
    spike_limit_percentage: 30
  batch:
    timeout: 10s
    send_batch_size: 10000
    send_batch_max_size: 11000
extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [memory_limiter, batch]
      exporters: [otlp]
  telemetry:
    logs:
      level: "debug"
